

services:
  reporter:
    build: .
    container_name: tg-reporter
    volumes:
      - .:/app
    stdin_open: true # Нужно для первого запуска, чтобы ввести код из СМС
    tty: true
    environment:
      - API_ID
      - API_HASH
      - PHONE
      - PYTHONUNBUFFERED=1
      
